# Generated by Django 5.2.17 on 2026-08-19 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='correo electronico')),
                ('nombre_completo', models.CharField(max_length=180, verbose_name='nombre completo')),
                ('rol', models.CharField(choices=[('ABOGADO', 'Abogado'), ('JURIDICA', 'Juridica'), ('ADMIN', 'Administrador')], default='ABOGADO', max_length=20, verbose_name='rol')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar.', verbose_name='activo')),
                ('disponible_para_asignacion', models.BooleanField(default=True, help_text='Vacaciones, incapacidad o carga excepcional.', verbose_name='disponible para asignacion')),
                ('peso_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Tope opcional de carga.', max_digits=6, null=True, verbose_name='peso maximo de carga')),
                ('ultima_asignacion', models.DateTimeField(blank=True, db_index=True, help_text='Criterio de desempate en el reparto.', null=True, verbose_name='ultima asignacion')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite acceder al sitio de administracion de Django.', verbose_name='acceso al admin')),
                ('ultimo_cambio_password', models.DateTimeField(blank=True, null=True, verbose_name='ultimo cambio de password')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
                'ordering': ['nombre_completo'],
                'indexes': [models.Index(fields=['rol', 'activo', 'disponible_para_asignacion'], name='idx_candidatos_asignacion')],
            },
        ),
    ]
